const W = 1800
const H = 900
const IS = 100
const LUCKY = 80
const LUCKY_DEC = 1
const AVATAR_SIZE = 400
const AVATAR_BORDER = 50
const AVATAR_STROKE = 25
const BALLE_SIZE = 70
const BALLE_STROKE = 6

export { W, H, IS, LUCKY, LUCKY_DEC, AVATAR_SIZE, AVATAR_BORDER, AVATAR_STROKE, BALLE_SIZE, BALLE_STROKE }